### Регистрация пользователя
POST {{$dotenv BASE_URL}}/user/auth/register
Content-Type: application/json

{
  "name": "Alice Example",
  "email": "alice@example.com",
  "password": "securepass",
  "phone": "+1234567890",
  "address": "123 Wonderland St"
}

###

### Авторизация пользователя
POST {{$dotenv BASE_URL}}/user/auth/login
Content-Type: application/json

{
  "email": "alice@example.com",
  "password": "securepass"
}
